OREAL_MOUSE_EVENT_EXT = "orme"
OREAL_COMPLETE_AVI_FILE_EXT = "oreal"
OREAL_DEFAULT_VIDEO_EXT = "avi"
OREAL_DEFAULT_AUDIO_EXT = "wav"
OREAL_COMPLETE_FILE_HEADER = "OREAL"
OREAL_OUTPUT_DIR = "output/"

OREAL_APP_NAME = "OReal"
OREAL_APP_DESCRIPTION = "OReal is a tool for recording top notch Video Tutorials."
OREAL_FEED_WEB_PAGE = "https://www.example.com"
